import turtle

wn = turtle.Screen()
wn.bgcolor("black")
wn.setup(width=1280, height=720)


blueRocket2 = turtle.Turtle()
blueRocket2.hideturtle()
blueRocket2.penup()
blueRocket2.color("blue")
blueRocket2.shape("square")
blueRocket2.shapesize(0.5, 0.5)
blueRocket2.goto(-400, -50)

blueRocket3 = turtle.Turtle()
blueRocket3.hideturtle()
blueRocket3.penup()
blueRocket3.color("blue")
blueRocket3.shape("square")
blueRocket3.shapesize(0.5, 0.5)
blueRocket3.goto(-400, -50)

blueRocket4 = turtle.Turtle()
blueRocket4.hideturtle()
blueRocket4.penup()
blueRocket4.color("blue")
blueRocket4.shape("square")
blueRocket4.shapesize(0.5, 0.5)
blueRocket4.goto(-400, -50)

blueRocket5 = turtle.Turtle()
blueRocket5.hideturtle()
blueRocket5.penup()
blueRocket5.color("blue")
blueRocket5.shape("square")
blueRocket5.shapesize(0.5, 0.5)
blueRocket5.goto(-400, -50)

blueRocket6 = turtle.Turtle()
blueRocket6.hideturtle()
blueRocket6.penup()
blueRocket6.color("blue")
blueRocket6.shape("square")
blueRocket6.shapesize(0.5, 0.5)
blueRocket6.goto(-400, -50)

blueRocket7 = turtle.Turtle()
blueRocket7.hideturtle()
blueRocket7.penup()
blueRocket7.color("blue")
blueRocket7.shape("square")
blueRocket7.shapesize(0.5, 0.5)
blueRocket7.goto(-400, -50)

blueRocket8 = turtle.Turtle()
blueRocket8.hideturtle()
blueRocket8.penup()
blueRocket8.color("blue")
blueRocket8.shape("square")
blueRocket8.shapesize(0.5, 0.5)
blueRocket8.goto(-400, -50)

# ________________________________________

purpleRocket2 = turtle.Turtle()
purpleRocket2.hideturtle()
purpleRocket2.penup()
purpleRocket2.color("purple")
purpleRocket2.shape("square")
purpleRocket2.shapesize(0.5, 0.5)
purpleRocket2.goto(300, -50)

purpleRocket3 = turtle.Turtle()
purpleRocket3.hideturtle()
purpleRocket3.penup()
purpleRocket3.color("purple")
purpleRocket3.shape("square")
purpleRocket3.shapesize(0.5, 0.5)
purpleRocket3.goto(300, -50)

purpleRocket4 = turtle.Turtle()
purpleRocket4.hideturtle()
purpleRocket4.penup()
purpleRocket4.color("purple")
purpleRocket4.shape("square")
purpleRocket4.shapesize(0.5, 0.5)
purpleRocket4.goto(300, -50)

purpleRocket5 = turtle.Turtle()
purpleRocket5.hideturtle()
purpleRocket5.penup()
purpleRocket5.color("purple")
purpleRocket5.shape("square")
purpleRocket5.shapesize(0.5, 0.5)
purpleRocket5.goto(300, -50)

purpleRocket6 = turtle.Turtle()
purpleRocket6.hideturtle()
purpleRocket6.penup()
purpleRocket6.color("purple")
purpleRocket6.shape("square")
purpleRocket6.shapesize(0.5, 0.5)
purpleRocket6.goto(300, -50)

purpleRocket7 = turtle.Turtle()
purpleRocket7.hideturtle()
purpleRocket7.penup()
purpleRocket7.color("purple")
purpleRocket7.shape("square")
purpleRocket7.shapesize(0.5, 0.5)
purpleRocket7.goto(300, -50)

purpleRocket8 = turtle.Turtle()
purpleRocket8.hideturtle()
purpleRocket8.penup()
purpleRocket8.color("purple")
purpleRocket8.shape("square")
purpleRocket8.shapesize(0.5, 0.5)
purpleRocket8.goto(300, -50)

# ________________________________________

